### ISSUE TITLE
Build errors on Slackware 14.1

### ISSUE THREAD

**Issue by PaulBatchelor** [andrewrk/libsoundio#14] opened 2015-09-04 05:29 UTC
I am currently trying to build libsoundio on Slackware. I already had to remove the "-wno-c99-extensions" as my version of GCC didn't seem to have that option. After fixing that issues, I'm left with this error I can't seem to get past:

/home/paul/playground/libsoundio/src/jack.cpp: In function 'int soundio_jack_init(SoundIoPrivate*)':
/home/paul/playground/libsoundio/src/jack.cpp:917:84: error: invalid conversion from 'void (*)(jack_port_id_t, const char*, const char*, void*) {aka void (*)(unsigned int, const char*, const char*, void*)}' to 'JackPortRenameCallback {aka int (*)(unsigned int, const char*, const char*, void*)}' [-fpermissive]
     if ((err = jack_set_port_rename_callback(sij->client, port_rename_calllback, si))) {
                                                                                    ^
make[2]: *** [CMakeFiles/libsoundio_shared.dir/src/jack.cpp.o] Error 1
make[1]: *** [CMakeFiles/libsoundio_shared.dir/all] Error 2
make: *** [all] Error 2

Some more info:

Linux: Slackware 14.1 (64 bit)
GCC 4.8.2
JACK 1.9.10 

Thanks!

**Comment by andrewrk** [comment] 2015-09-04 05:51
Duplicate of #7 

Let me know if you still need help after reading that other issue.

**Closed by andrewrk** 2015-09-04 05:51 UTC
Labels: duplicate
