### ISSUE TITLE
Can't build libsoundio 1.0.3

### ISSUE THREAD

**Issue by klingtnet** [andrewrk/libsoundio#54] opened 2016-01-20 23:21 UTC
I wanted to build libsoudio version 1.0.3 under Arch Linux but `make` failed with the following message:

```
/home/andreas/personal/dev/c/libsoundio/src/jack.cpp: In function ‘int soundio_jack_init(SoundIoPrivate*)’:
/home/andreas/personal/dev/c/libsoundio/src/jack.cpp:919:84: error: invalid conversion from ‘void (*)(jack_port_id_t, const char*, const char*, void*) {aka void (*)(unsigned int, const char*, const char*, void*)}’ to ‘JackPortRenameCallback {aka int (*)(unsigned int, const char*, const char*, void*)}’ [-fpermissive]
     if ((err = jack_set_port_rename_callback(sij->client, port_rename_calllback, si))) {
                                                                                    ^
In file included from /home/andreas/personal/dev/c/libsoundio/src/jack.hpp:15:0,
                 from /home/andreas/personal/dev/c/libsoundio/src/jack.cpp:8:
/usr/include/jack/jack.h:523:5: note:   initializing argument 2 of ‘int jack_set_port_rename_callback(jack_client_t*, JackPortRenameCallback, void*)’
 int jack_set_port_rename_callback (jack_client_t *client,
     ^
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-c99-extensions’ [-Werror]
cc1plus: all warnings being treated as errors
CMakeFiles/libsoundio_shared.dir/build.make:206: recipe for target 'CMakeFiles/libsoundio_shared.dir/src/jack.cpp.o' failed
make[2]: *** [CMakeFiles/libsoundio_shared.dir/src/jack.cpp.o] Error 1
CMakeFiles/Makefile2:205: recipe for target 'CMakeFiles/libsoundio_shared.dir/all' failed
make[1]: *** [CMakeFiles/libsoundio_shared.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Steps to reproduce the error:

- `git clone git@github.com:andrewrk/libsoundio.git && cd libsoundio && git checkout 1.0.3`
- `mkdir build && cd build`
- `cmake ..`
- `make`

The cmake output looks fine:

```
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Configuring libsoundio version 1.0.3
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found JACK: /usr/lib64/libjack.so  
-- Found PULSEAUDIO: /usr/lib64/libpulse.so  
-- Found ALSA: /usr/lib64/libasound.so (found version "1.1.0") 
-- Could NOT find COREAUDIO (missing:  COREAUDIO_LIBRARY COREAUDIO_INCLUDE_DIR) 
-- Could NOT find WASAPI (missing:  WASAPI_INCLUDE_DIR) 

Installation Summary
--------------------
* Install Directory            : /usr/local
* Build Type                   : Debug
* Build static libs            : ON
* Build examples               : ON
* Build tests                  : ON

System Dependencies
-------------------
* threads                      : OK
* JACK       (optional)        : OK
* PulseAudio (optional)        : OK
* ALSA       (optional)        : OK
* CoreAudio  (optional)        : not found
* WASAPI     (optional)        : not found

-- Configuring done
-- Generating done
-- Build files have been written to: /home/andreas/personal/dev/c/libsoundio/build
```

**Comment by andrewrk** [comment] 2016-01-20 23:29
Looks like a duplicate of #7. See the resolution in that thread. Feel free to comment further if you have more questions.

**Closed by andrewrk** 2016-01-20 23:29 UTC

**Comment by klingtnet** [comment] 2016-01-20 23:39
Thank you for your fast response, but I've already installed the latest release `1.9.10` via the [`jack2-dbus`](https://wiki.archlinux.org/index.php/JACK_Audio_Connection_Kit#JACK2_D-Bus) package. Updating Jack2 won't fix the problem I guess.

**Comment by andrewrk** [comment] 2016-01-20 23:47
In that case, sadly, it means the arch package does not conform to the JACK API.

The resolution is the same. Choose one of:

 * Convince the team who made the arch package to include the patch and release a new package.
 * Compile jack2-dbus yourself with the patch and install it to your system.
 * Compile libsoundio without JACK support.
 * Fork libsoundio (or just edit the source) and change that void to an int to work with the older jack2 version.

**Comment by klingtnet** [comment] 2016-01-20 23:53
Thank you for your response, I think I will choose solution number one and try to convince the package maintainer to include the patch.

**Comment by andrewrk** [comment] 2016-01-20 23:56
The most noble option!

To be clear, here is the patch: https://github.com/jackaudio/jack2/commit/05216197b491d64036733a2d3be511456c1f65cd

One argument to help your case is that the Debian package includes the patch.

Good luck!
