### ISSUE TITLE
Build error in jack.cpp

### ISSUE THREAD

**Issue by ianmacs** [andrewrk/libsoundio#41] opened 2015-10-31 08:49 UTC
```
[  2%] Building CXX object CMakeFiles/libsoundio_shared.dir/src/jack.cpp.o
/usr/bin/c++   -Dlibsoundio_shared_EXPORTS -g -Werror -pedantic -fPIC -I/home/ianmacs/dev/libsoundio -I/home/ianmacs/dev/libsoundio/build -I/home/ianmacs/dev/libsoundio/test -I/home/ianmacs/dev/libsoundio/src    -std=c++11 -fno-exceptions -fno-rtti -fvisibility=hidden -Wall -Werror=strict-prototypes -Werror=old-style-definition -Werror=missing-prototypes -Wno-c99-extensions -o CMakeFiles/libsoundio_shared.dir/src/jack.cpp.o -c /home/ianmacs/dev/libsoundio/src/jack.cpp
/home/ianmacs/dev/libsoundio/src/jack.cpp: In function ‘int soundio_jack_init(SoundIoPrivate*)’:
/home/ianmacs/dev/libsoundio/src/jack.cpp:913:84: error: invalid conversion from ‘void (*)(jack_port_id_t, const char*, const char*, void*) {aka void (*)(unsigned int, const char*, const char*, void*)}’ to ‘JackPortRenameCallback {aka int (*)(unsigned int, const char*, const char*, void*)}’ [-fpermissive]
     if ((err = jack_set_port_rename_callback(sij->client, port_rename_calllback, si))) {
                                                                                    ^
At global scope:
cc1plus: error: unrecognized command line option "-Wno-c99-extensions" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/libsoundio_shared.dir/src/jack.cpp.o] Error 1
make[2]: Leaving directory `/home/ianmacs/dev/libsoundio/build'
make[1]: *** [CMakeFiles/libsoundio_shared.dir/all] Error 2
make[1]: Leaving directory `/home/ianmacs/dev/libsoundio/build'
make: *** [all] Error 2
```

This is on ubuntu 14.04, jack development package is libjack-jackd2-dev version 1.9.9.5+20130622git7de15e7a-1ubuntu1, compiler is g++-4.8.4

**Comment by ianmacs** [comment] 2015-10-31 08:57
This fixes the build but might break other things:

```
diff --git a/src/jack.cpp b/src/jack.cpp
index 2ffd9b7..1291404 100644
--- a/src/jack.cpp
+++ b/src/jack.cpp
@@ -827,11 +827,12 @@ static void port_registration_callback(jack_port_id_t port_id, int reg, void *ar
     notify_devices_change(si);
 }
 
-static void port_rename_calllback(jack_port_id_t port_id,
+static int port_rename_calllback(jack_port_id_t port_id,
         const char *old_name, const char *new_name, void *arg)
 {
     SoundIoPrivate *si = (SoundIoPrivate *)arg;
     notify_devices_change(si);
+    return 0;
 }
 
 static void shutdown_callback(void *arg) {
```

**Comment by diogocp** [comment] 2015-10-31 20:51
That jack2 version is too old, see #7.

**Comment by andrewrk** [comment] 2015-10-31 22:06
Indeed, this issue is a duplicate of #7.

**Closed by andrewrk** 2015-10-31 22:06 UTC
